variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'DFC.App.JobGroups'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:

  - job: BuildTestAndAnalyze
    displayName: "Test & package ARM template(s)"
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - task: PublishPipelineArtifact@1
      displayName: Publish Apim Policy
      inputs:
        targetPath: "$(Build.SourcesDirectory)/Resources/ApimPolicy"
        artifactName: ${{ variables.SolutionBaseName }}.ApimPolicies

    - task: PublishPipelineArtifact@1
      displayName: Publish OpenAPI docs to Pipeline Artifact
      inputs:
        targetPath: "$(Build.SourcesDirectory)/DFC.App.JobGroups/OpenAPIDocs"
        artifactName: ${{ variables.SolutionBaseName }}.OpenAPIDocs

    - task: PublishPipelineArtifact@1
      displayName: Publish API import script to Pipeline Artifact
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Resources/Scripts"
        artifactName: ${{ variables.SolutionBaseName }}.Scripts

    - task: PublishPipelineArtifact@0
      displayName: Publish Page Registration artifact
      inputs:
        targetPath: '$(Build.SourcesDirectory)/Resources/PageRegistration'
        artifactName: ${{ variables.SolutionBaseName }}.PageRegistrations

  - job: BuildDotNetCore
    displayName: Build-DotNetCore
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests

- stage: DeployToDevAppJobGroups
  # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  condition: succeeded()
  displayName: Deploy to DEV_AppJobGroups
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-dev
  - group: dfc-compositeui-all
  - template: VariableTemplates\DevEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_AppJobGroups
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      AppRegistryApiUrl: "$(AppRegistryApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)
      SharedResourceGroupName: $(SharedResourceGroupName)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      ApiName: $(ApiName)
      ApiId: $(ApiId)
      FunctionAppDomain: $(FunctionAppDomain)
      ApiDefinitionPath: $(ApiDefinitionPath)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"

- stage: DeployToDevDraftAppJobGroups
  condition: succeeded()
  displayName: Deploy to DEV-DRAFT_AppJobGroups
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-draft
  - group: dfc-app-shared-registration-draft
  - group: dfc-stax-shared-dev
  - group: dfc-compositeui-all
  - template: VariableTemplates\DevDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV-DRAFT_AppJobGroups
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      AppRegistryApiUrl: "$(AppRegistryApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)
      SharedResourceGroupName: $(SharedResourceGroupName)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      ApiName: $(ApiName)
      ApiId: $(ApiId)
      FunctionAppDomain: $(FunctionAppDomain)
      ApiDefinitionPath: $(ApiDefinitionPath)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"

- stage: DeployToSitAppJobGroups
  condition: succeeded()
  displayName: Deploy to SIT_AppJobGroups
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-sit
  - group: dfc-compositeui-all
  - template: VariableTemplates\SitEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT_AppJobGroups
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      AppRegistryApiUrl: "$(AppRegistryApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)
      SharedResourceGroupName: $(SharedResourceGroupName)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      ApiName: $(ApiName)
      ApiId: $(ApiId)
      FunctionAppDomain: $(FunctionAppDomain)
      ApiDefinitionPath: $(ApiDefinitionPath)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"

- stage: DeployToSitDraftAppJobGroups
  condition: succeeded()
  displayName: Deploy to SIT-DRAFT_AppJobGroups
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-draft
  - group: dfc-app-shared-registration-draft
  - group: dfc-stax-shared-sit
  - group: dfc-compositeui-all
  - template: VariableTemplates\SitDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT-DRAFT_AppJobGroups
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      AppRegistryApiUrl: "$(AppRegistryApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)
      SharedResourceGroupName: $(SharedResourceGroupName)
      ApimServiceName: $(ApimServiceName)
      ApimProductInstanceName: $(ApimProductInstanceName)
      ApiName: $(ApiName)
      ApiId: $(ApiId)
      FunctionAppDomain: $(FunctionAppDomain)
      ApiDefinitionPath: $(ApiDefinitionPath)
      APIMPolicyPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.ApimPolicies/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.OpenApiDocs"