variables:
- name: ReleaseEnvironmentName
  value: sit
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDbCollectionName
  value: job-groups
- name: sharedContentDbCollectionName
  value: shared-content
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.JobGroups
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-jobgroups
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-sit-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/jobgroups
- name: apiName
  value: jobgroups
- name: apiId
  value: composite-ui-jobgroups
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-sit-app-jobgroups
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: 2c9da1b3-3529-4834-afc9-9cd741e59788
- name: EnableAzureMonitorAlerting
  value: true
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: clientAffinity
  value: false
- name: jobgroupsAppDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-sit-app-jobgroups-as.$(FunctionAppDomain)/lmi-delta-report
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/